version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: api_sazon_criollo_php
    volumes:
      - ./api:/var/www/html
    env_file:
      - .env
    networks:
      - api_sazon_criollo_net

  nginx:
    image: nginx:alpine
    container_name: api_sazon_criollo_nginx
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - api_sazon_criollo_net

networks:
  api_sazon_criollo_net:
    driver: bridge
